# Generated by Django 4.2.6 on 2024-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('desc', models.TextField(default='', max_length=300)),
            ],
        ),
    ]
