# Generated by Django 4.2.6 on 2024-03-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_category_subcategory_category_category_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='parent',
        ),
    ]
