# Generated by Django 5.0.3 on 2024-04-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customerorder_remove_addcart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='itemjson',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='productDetails',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='totalprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='address',
            field=models.TextField(),
        ),
    ]
