# Generated by Django 5.0.3 on 2024-04-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_coupencode_remove_customerorder_productdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.IntegerField(default=0, verbose_name='Profit on Product(%)'),
        ),
    ]
