# Generated by Django 5.0.3 on 2024-04-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_product_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupencode',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount(%)'),
        ),
    ]
