# Generated by Django 5.0.3 on 2024-04-30 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_updatestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
