# Generated by Django 5.0.3 on 2024-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Done', 'Done')], default='Processing', max_length=20),
        ),
    ]
