# Generated by Django 5.0.3 on 2024-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Done', 'Done')], default='Processing', max_length=20),
        ),
    ]
