# Generated by Django 5.0.3 on 2024-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_cacnceledorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacnceledorder',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
